FROM node:latest

WORKDIR /opt/cion/cion-node-server

RUN apt-get install && apt-get update

COPY package*.json /opt/cion/cion-node-server

RUN npm install

COPY . /opt/cion/cion-node-server

CMD ["npm","start"]